<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { BellRing, LoaderCircle, Plus, Trash2, X } from "lucide-vue-next";
import { api, apiError, notify } from "../services/api";
import { dateTime } from "../services/format";
import type { AdminTenant, PagedResult, PlatformNotification } from "../types/api";

const notifications = ref<PlatformNotification[]>([]), tenants = ref<AdminTenant[]>([]), loading = ref(false), saving = ref(false), error = ref(""), showModal = ref(false);
const form = reactive({ title: "", message: "", severity: "info", targetTenantId: "" });
async function load() { loading.value = true; error.value = ""; try { const [announcements, tenantResult] = await Promise.all([api.get<PlatformNotification[]>("/superadmin/notifications"), api.get<PagedResult<AdminTenant>>("/admin/tenants", { params: { pageNumber: 1, pageSize: 50 } })]); notifications.value = announcements.data; tenants.value = tenantResult.data.items; } catch (cause) { error.value = apiError(cause); } finally { loading.value = false; } }
function open() { Object.assign(form, { title: "", message: "", severity: "info", targetTenantId: "" }); error.value = ""; showModal.value = true; }
async function save() { if (!form.title.trim() || !form.message.trim()) { error.value = "Completá el título y el mensaje."; return; } saving.value = true; try { const { data } = await api.post<PlatformNotification>("/superadmin/notifications", { ...form, targetTenantId: form.targetTenantId || null }); notifications.value = [data, ...notifications.value]; showModal.value = false; notify("Anuncio publicado."); } catch (cause) { error.value = apiError(cause); } finally { saving.value = false; } }
async function remove(item: PlatformNotification) { if (!window.confirm(`¿Eliminar el anuncio “${item.title}”?`)) return; try { await api.delete(`/superadmin/notifications/${item.id}`); notifications.value = notifications.value.filter(current => current.id !== item.id); notify("Anuncio eliminado."); } catch (cause) { error.value = apiError(cause); } }
</script>

<template>
  <div class="page-heading"><div><div class="breadcrumb">SuperAdmin / Anuncios</div><h1>Notificaciones y anuncios</h1><p>Comunicá novedades a todas las empresas o a un negocio específico.</p></div><button class="primary" @click="open"><Plus :size="17" />Nuevo anuncio</button></div>
  <section class="panel"><p v-if="error" class="error" role="alert">{{ error }}</p><p v-else-if="loading" class="empty-small">Cargando anuncios…</p><div v-else-if="notifications.length" class="responsive-table"><table><thead><tr><th>Anuncio</th><th>Alcance</th><th>Tipo</th><th>Fecha</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="item in notifications" :key="item.id"><td><strong>{{ item.title }}</strong><small>{{ item.message }}</small></td><td>{{ item.targetTenantName || "Todas las empresas" }}</td><td><span class="severity" :class="item.severity">{{ item.severity }}</span></td><td>{{ dateTime(item.createdAtUtc) }}</td><td><span class="status" :class="item.isActive ? 'success-status' : 'danger'">{{ item.isActive ? "Activo" : "Inactivo" }}</span></td><td><button class="icon-button danger-button" title="Eliminar anuncio" @click="remove(item)"><Trash2 :size="17" /></button></td></tr></tbody></table></div><div v-else class="empty-state compact"><BellRing :size="34" /><h2>Todavía no hay anuncios</h2><p>Publicá el primero para comunicarte con tus clientes.</p></div></section>
  <div v-if="showModal" class="modal-backdrop"><section class="modal announcement-modal"><button class="icon-button modal-close" aria-label="Cerrar" @click="showModal = false"><X /></button><div class="modal-icon"><BellRing /></div><h2>Nuevo anuncio</h2><p>El anuncio aparecerá en la campanita de las empresas alcanzadas.</p><form novalidate @submit.prevent="save"><label>Título<input v-model.trim="form.title" maxlength="200" required /></label><label>Mensaje<textarea v-model.trim="form.message" rows="5" maxlength="2000" required /></label><div class="form-grid"><label>Tipo<select v-model="form.severity"><option value="info">Informativo</option><option value="warning">Advertencia</option><option value="success">Éxito</option></select></label><label>Destino<select v-model="form.targetTenantId"><option value="">Todas las empresas</option><option v-for="tenant in tenants" :key="tenant.id" :value="tenant.id">{{ tenant.name }}</option></select></label></div><p v-if="error" class="error">{{ error }}</p><button class="primary full" :disabled="saving"><LoaderCircle v-if="saving" class="spin" :size="16" />{{ saving ? "Publicando…" : "Publicar anuncio" }}</button></form></section></div>
</template>

<style scoped>
td small{display:block;max-width:28rem;margin-top:.25rem;color:#64748b}.severity{display:inline-flex;padding:.25rem .5rem;border-radius:999px;background:#dbeafe;color:#1d4ed8;font-size:.72rem;font-weight:750;text-transform:capitalize}.severity.warning{background:#fef3c7;color:#92400e}.severity.success{background:#d1fae5;color:#047857}.danger-button{color:#e11d48}.announcement-modal{max-width:36rem}.dark td small{color:#b8c7dc}.dark .severity.info{background:#1e3a5f;color:#bfdbfe}.dark .severity.warning{background:#3d3013;color:#fde68a}.dark .severity.success{background:#173a35;color:#a7f3d0}
</style>
