<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { CheckCircle2, Clock3, PauseCircle, RefreshCw, Search, ShieldAlert, UserRoundCheck, X } from "lucide-vue-next";
import { api, apiError, notify } from "../services/api";
import { dateTime, money } from "../services/format";
import TablePaginator from "../components/TablePaginator.vue";
import type { AdminPlan, AdminTenant, AuthResponse, PagedResult } from "../types/api";
import { useAuthStore } from "../stores/auth";
import { useTenantStore } from "../stores/tenant";
import { useRouter } from "vue-router";

const auth = useAuthStore(), tenantStore = useTenantStore(), router = useRouter();
const result = ref<PagedResult<AdminTenant> | null>(null), plans = ref<AdminPlan[]>([]), search = ref(""), page = ref(1), loading = ref(false), error = ref(""), actioning = ref(""), supportTenant = ref<AdminTenant | null>(null), supportReason = ref(""), supportError = ref("");
const selectedPlans = ref<Record<string, string>>({});
const pageSize = 15;
const tenants = computed(() => result.value?.items || []);
const statusClass = (tenant: AdminTenant) => tenant.status === "Suspendida" ? "danger" : tenant.status === "Trial" ? "trial" : tenant.status === "Activa" ? "success-status" : "warning";
async function load() { loading.value = true; error.value = ""; try { const [tenantsResponse, plansResponse] = await Promise.all([api.get<PagedResult<AdminTenant>>("/admin/tenants", { params: { pageNumber: page.value, pageSize, search: search.value.trim() || undefined } }), api.get<AdminPlan[]>("/admin/plans")]); result.value = tenantsResponse.data; plans.value = plansResponse.data; for (const tenant of tenantsResponse.data.items) selectedPlans.value[tenant.id] ??= tenant.subscriptionPlanId || ""; } catch (cause) { error.value = apiError(cause); } finally { loading.value = false; } }
function replace(updated: AdminTenant) { if (!result.value) return; result.value.items = result.value.items.map(item => item.id === updated.id ? updated : item); selectedPlans.value[updated.id] = updated.subscriptionPlanId || ""; }
async function extendTrial(tenant: AdminTenant) { if (!window.confirm(`¿Extender 7 días la prueba de ${tenant.name}?`)) return; actioning.value = tenant.id; try { replace((await api.post<AdminTenant>(`/admin/tenants/${tenant.id}/extend-trial`, { days: 7 })).data); notify("Prueba extendida por 7 días."); } catch (cause) { notify(apiError(cause), true); } finally { actioning.value = ""; } }
async function changePlan(tenant: AdminTenant) { const planId = selectedPlans.value[tenant.id]; if (!planId || planId === tenant.subscriptionPlanId) return; if (!window.confirm(`¿Asignar este plan manualmente a ${tenant.name}?`)) { selectedPlans.value[tenant.id] = tenant.subscriptionPlanId || ""; return; } actioning.value = tenant.id; try { replace((await api.post<AdminTenant>(`/admin/tenants/${tenant.id}/change-plan`, { subscriptionPlanId: planId })).data); notify("Plan actualizado manualmente."); } catch (cause) { selectedPlans.value[tenant.id] = tenant.subscriptionPlanId || ""; notify(apiError(cause), true); } finally { actioning.value = ""; } }
async function toggleAccess(tenant: AdminTenant) { const isActive = !tenant.isActive; if (!window.confirm(`${isActive ? "¿Activar" : "¿Suspender"} el acceso de ${tenant.name}?`)) return; actioning.value = tenant.id; try { replace((await api.post<AdminTenant>(`/admin/tenants/${tenant.id}/access`, { isActive })).data); notify(isActive ? "Acceso activado." : "Acceso suspendido."); } catch (cause) { notify(apiError(cause), true); } finally { actioning.value = ""; } }
function openSupport(tenant: AdminTenant) { supportTenant.value = tenant; supportReason.value = ""; supportError.value = ""; }
async function startSupport() { if (!supportTenant.value) return; if (supportReason.value.trim().length < 10) { supportError.value = "Indicá un motivo de al menos 10 caracteres."; return; } actioning.value = supportTenant.value.id; supportError.value = ""; try { const { data } = await api.post<AuthResponse>(`/admin/tenants/${supportTenant.value.id}/impersonate`, { reason: supportReason.value.trim() }); auth.beginImpersonation(data); tenantStore.reset(); await router.replace("/dashboard"); notify(`Sesión de soporte iniciada para ${supportTenant.value.name}.`); } catch (cause) { supportError.value = apiError(cause); } finally { actioning.value = ""; } }
watch(search, () => { page.value = 1; void load(); });
onMounted(load);
</script>

<template>
  <div class="page-heading"><div><div class="breadcrumb">SuperAdmin / Empresas</div><h1>Empresas registradas</h1><p>Administrá el acceso y la suscripción de cada negocio de la plataforma.</p></div><button class="secondary" :disabled="loading" @click="load"><RefreshCw :size="16" :class="{ spin: loading }" />Actualizar</button></div>
  <section class="panel admin-tenants-panel"><div class="admin-table-toolbar"><label><span class="sr-only">Buscar empresa</span><Search :size="17" /><input v-model.trim="search" placeholder="Buscar por empresa o CUIT" /></label></div><p v-if="error" class="error" role="alert">{{ error }}</p><p v-else-if="loading && !result" class="empty-small">Cargando empresas…</p><div v-else-if="tenants.length" class="responsive-table"><table><thead><tr><th>Empresa</th><th>CUIT</th><th>Plan actual</th><th>Estado</th><th>Fecha de alta</th><th>Acciones</th></tr></thead><tbody><tr v-for="tenant in tenants" :key="tenant.id"><td><strong>{{ tenant.name }}</strong></td><td>{{ tenant.taxId || "—" }}</td><td><div class="plan-change"><select v-model="selectedPlans[tenant.id]" :disabled="actioning === tenant.id"><option value="" disabled>Sin plan</option><option v-for="plan in plans" :key="plan.id" :value="plan.id">{{ plan.name }} · {{ money(plan.monthlyPrice) }}/mes</option></select><button class="secondary compact" :disabled="actioning === tenant.id || selectedPlans[tenant.id] === tenant.subscriptionPlanId" @click="changePlan(tenant)">Cambiar</button></div></td><td><span class="status" :class="statusClass(tenant)">{{ tenant.status }}</span></td><td>{{ dateTime(tenant.createdAtUtc) }}</td><td><div class="admin-actions"><button class="secondary compact support-action" :disabled="actioning === tenant.id || !tenant.isActive" @click="openSupport(tenant)"><UserRoundCheck :size="15" />Soporte</button><button v-if="tenant.status === 'Trial'" class="secondary compact" :disabled="actioning === tenant.id" @click="extendTrial(tenant)"><Clock3 :size="15" />Extender prueba</button><button class="compact" :class="tenant.isActive ? 'danger-action' : 'secondary'" :disabled="actioning === tenant.id" @click="toggleAccess(tenant)"><PauseCircle v-if="tenant.isActive" :size="15" /><CheckCircle2 v-else :size="15" />{{ tenant.isActive ? 'Suspender' : 'Activar' }}</button></div></td></tr></tbody></table></div><div v-else class="empty-state compact"><ShieldAlert :size="34" /><h2>No hay empresas para mostrar</h2><p>Probá cambiar la búsqueda.</p></div><TablePaginator v-if="result" :page="result.pageNumber" :total-pages="result.totalPages" :total-count="result.totalCount" :shown-count="tenants.length" :page-size="result.pageSize" @previous="page -= 1; load()" @next="page += 1; load()" /></section>
  <div v-if="supportTenant" class="modal-backdrop"><section class="modal support-modal" role="dialog" aria-modal="true" aria-labelledby="support-title"><button class="icon-button modal-close" aria-label="Cerrar" @click="supportTenant = null"><X :size="20" /></button><div class="modal-icon"><UserRoundCheck /></div><h2 id="support-title">Ingresar para soporte</h2><p>Vas a operar como el usuario titular de <strong>{{ supportTenant.name }}</strong>. No se usa ni se muestra su contraseña. La sesión y los cambios quedarán auditados.</p><p v-if="supportError" class="error" role="alert">{{ supportError }}</p><label>Motivo de soporte<textarea v-model.trim="supportReason" rows="4" maxlength="500" placeholder="Ej.: Revisar un inconveniente reportado en facturación."></textarea><small>Mínimo 10 caracteres. Este motivo queda registrado.</small></label><button class="primary full" :disabled="actioning === supportTenant.id" @click="startSupport"><UserRoundCheck :size="17" />{{ actioning === supportTenant.id ? 'Iniciando…' : 'Ingresar como titular' }}</button></section></div>
</template>

<style scoped>
.admin-tenants-panel{padding:1.1rem}.admin-table-toolbar{display:flex;justify-content:flex-end;margin-bottom:1rem}.admin-table-toolbar label{display:flex;align-items:center;gap:.5rem;width:min(22rem,100%);padding:0 .7rem;border:1px solid #dbe3ef;border-radius:.65rem;color:#64748b}.admin-table-toolbar input{border:0;box-shadow:none}.plan-change,.admin-actions{display:flex;align-items:center;gap:.45rem}.plan-change select{min-width:12rem;padding:.52rem}.compact{display:inline-flex;align-items:center;justify-content:center;gap:.3rem;min-height:2rem;padding:.4rem .58rem;border-radius:.5rem;font-size:.73rem;font-weight:700;white-space:nowrap}.danger-action{border:1px solid #fecdd3;background:#fff1f2;color:#be123c}.danger-action:hover{background:#ffe4e6}.trial{background:#ede9fe;color:#6d28d9}.warning{background:#fef3c7;color:#92400e}.support-action{border-color:#c4b5fd;color:#6d28d9}.support-modal{max-width:31rem}.support-modal label{display:grid;gap:.45rem;margin-top:1rem}.support-modal textarea{resize:vertical}.support-modal small{color:#64748b}.dark .admin-table-toolbar label{border-color:#475a77;background:#0f172a}.dark .admin-table-toolbar input{background:transparent}.dark .danger-action{border-color:#9f1239;background:#3b1726;color:#fecdd3}@media(max-width:900px){.admin-table-toolbar{justify-content:stretch}.admin-table-toolbar label{width:100%}.plan-change,.admin-actions{align-items:flex-start;flex-direction:column}}
</style>
