<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { LoaderCircle, RefreshCw, Save, Tags } from "lucide-vue-next";
import { api, apiError, notify } from "../services/api";
import { money } from "../services/format";
import type { AdminPlan } from "../types/api";

type PlanForm = Pick<AdminPlan, "monthlyPrice" | "annualPrice" | "maxUsers" | "maxWarehouses" | "maxInvoicesPerMonth" | "supportsAfip" | "isActive">;
const plans = ref<AdminPlan[]>([]), loading = ref(false), savingId = ref(""), error = ref("");
const forms = reactive<Record<string, PlanForm>>({});
const toForm = (plan: AdminPlan): PlanForm => ({ monthlyPrice: plan.monthlyPrice, annualPrice: plan.annualPrice, maxUsers: plan.maxUsers, maxWarehouses: plan.maxWarehouses, maxInvoicesPerMonth: plan.maxInvoicesPerMonth, supportsAfip: plan.supportsAfip, isActive: plan.isActive });
const activePlans = computed(() => plans.value.filter(plan => plan.isActive).length);
async function load() { loading.value = true; error.value = ""; try { plans.value = (await api.get<AdminPlan[]>("/admin/plans")).data; for (const plan of plans.value) forms[plan.id] = toForm(plan); } catch (cause) { error.value = apiError(cause); } finally { loading.value = false; } }
async function save(plan: AdminPlan) { const form = forms[plan.id]; if (!form) return; savingId.value = plan.id; try { const { data } = await api.put<AdminPlan>(`/admin/plans/${plan.id}`, form); plans.value = plans.value.map(item => item.id === data.id ? data : item); forms[data.id] = toForm(data); notify(`Plan ${data.name} actualizado.`); } catch (cause) { notify(apiError(cause), true); } finally { savingId.value = ""; } }
onMounted(load);
</script>

<template>
  <div class="page-heading"><div><div class="breadcrumb">SuperAdmin / Planes</div><h1>Planes y precios</h1><p>Definí los importes y límites que verán los negocios al contratar KloverCloud.</p></div><button class="secondary" :disabled="loading" @click="load"><RefreshCw :size="16" :class="{ spin: loading }" />Actualizar</button></div>
  <section class="plans-note panel"><Tags :size="20" /><p><strong>{{ activePlans }} planes activos.</strong> Los cambios se aplican a nuevos checkouts; las suscripciones ya emitidas conservan su importe histórico.</p></section>
  <p v-if="error" class="error" role="alert">{{ error }}</p><div v-else-if="loading" class="empty-small"><LoaderCircle class="spin" /> Cargando planes…</div>
  <section v-else class="admin-plans-grid"><article v-for="plan in plans" :key="plan.id" class="plan-editor" :class="{ inactive: !forms[plan.id]?.isActive }"><header><div><span class="plan-status" :class="{ muted: !forms[plan.id]?.isActive }">{{ forms[plan.id]?.isActive ? "Disponible" : "No disponible" }}</span><h2>{{ plan.name }}</h2><small>{{ plan.isDefault ? "Plan inicial de nuevas empresas" : "Plan comercial" }}</small></div><strong>{{ money(forms[plan.id]?.monthlyPrice || 0) }}<small>/ mes</small></strong></header><form v-if="forms[plan.id]" @submit.prevent="save(plan)"><div class="plan-form-grid"><label>Precio mensual<input v-model.number="forms[plan.id].monthlyPrice" type="number" min="0" step="1" required /></label><label>Precio anual<input v-model.number="forms[plan.id].annualPrice" type="number" min="0" step="1" required /></label><label>Usuarios máximos<input v-model.number="forms[plan.id].maxUsers" type="number" min="1" step="1" required /></label><label>Depósitos máximos<input v-model.number="forms[plan.id].maxWarehouses" type="number" min="1" step="1" required /></label><label class="wide">Comprobantes por mes<input v-model.number="forms[plan.id].maxInvoicesPerMonth" type="number" min="1" step="1" required /></label></div><label class="plan-toggle"><input v-model="forms[plan.id].supportsAfip" type="checkbox" /><span>Incluye Facturación ARCA</span></label><label class="plan-toggle"><input v-model="forms[plan.id].isActive" type="checkbox" /><span>Mostrar este plan para nuevas contrataciones</span></label><button class="primary full" :disabled="savingId === plan.id"><LoaderCircle v-if="savingId === plan.id" class="spin" :size="16" /><Save v-else :size="16" />{{ savingId === plan.id ? "Guardando…" : "Guardar cambios" }}</button></form></article></section>
</template>

<style scoped>
.plans-note{display:flex;align-items:flex-start;gap:.65rem;margin-bottom:1rem;border-color:#fbcfe8;background:#fff7fb;color:#be185d}.plans-note p{margin:0;color:#475569}.plans-note svg{flex:0 0 auto;margin-top:.1rem}.admin-plans-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:1rem}.plan-editor{padding:1.2rem;border:1px solid #dbe3ef;border-radius:1rem;background:#fff;box-shadow:0 1px 2px rgba(15,23,42,.04)}.plan-editor.inactive{background:#f8fafc;opacity:.82}.plan-editor header{display:flex;justify-content:space-between;gap:1rem;margin-bottom:1.15rem}.plan-editor h2{margin:.45rem 0 .1rem}.plan-editor header small{color:#475569;font-size:.78rem;font-weight:500}.plan-editor header>strong{color:#0f172a;font-size:1.35rem;white-space:nowrap}.plan-editor header>strong small{font-size:.75rem;font-weight:500}.plan-status{display:inline-flex;padding:.2rem .45rem;border-radius:999px;background:#dcfce7;color:#166534;font-size:.68rem;font-weight:750}.plan-status.muted{background:#e2e8f0;color:#475569}.plan-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}.plan-form-grid label,.plan-toggle{display:grid;gap:.3rem;color:#334155;font-size:.8rem;font-weight:700}.plan-form-grid .wide{grid-column:span 2}.plan-form-grid input{padding:.58rem .7rem}.plan-toggle{grid-template-columns:auto 1fr;align-items:center;margin-top:.75rem;font-weight:600}.plan-toggle input{width:1rem;height:1rem;margin:0;accent-color:#ec4899}.plan-editor .primary{margin-top:1rem}@media(max-width:520px){.plan-form-grid{grid-template-columns:1fr}.plan-form-grid .wide{grid-column:span 1}}.dark .plan-editor{border-color:#334155;background:#172033}.dark .plan-editor.inactive{background:#111827}.dark .plan-editor header>strong,.dark .plan-form-grid label,.dark .plan-toggle{color:#e2e8f0}.dark .plans-note{background:#2e1930}.dark .plans-note p{color:#d1dced}
</style>
