<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from "vue";
import { CheckCircle2, LoaderCircle, MessageSquareText, RefreshCw, Search, Send, X } from "lucide-vue-next";
import { api, apiError, notify } from "../services/api";
import { dateTime } from "../services/format";
import type { SupportTicket } from "../types/api";

const tickets = ref<SupportTicket[]>([]), loading = ref(false), saving = ref(false), error = ref(""), search = ref(""), selected = ref<SupportTicket | null>(null);
const reply = reactive({ response: "", status: 3 });
const filtered = computed(() => { const term = search.value.trim().toLowerCase(); return term ? tickets.value.filter(ticket => [ticket.tenantName, ticket.userName, ticket.subject, ticket.message, ticket.response].some(value => String(value || "").toLowerCase().includes(term))) : tickets.value; });
const statusLabel = (status: number) => ({ 1: "Abierto", 2: "En progreso", 3: "Resuelto" }[status] || "Abierto");
const statusClass = (status: number) => ({ 1: "warning", 2: "trial", 3: "success-status" }[status] || "warning");
async function load(silent = false) { if (!silent) { loading.value = true; error.value = ""; } try { tickets.value = (await api.get<SupportTicket[]>("/superadmin/support")).data; } catch (cause) { if (!silent) error.value = apiError(cause); } finally { if (!silent) loading.value = false; } }
function open(ticket: SupportTicket) { selected.value = ticket; reply.response = ticket.response || ""; reply.status = ticket.status === 1 ? 3 : ticket.status; error.value = ""; }
async function saveReply() { if (!selected.value || !reply.response.trim()) { error.value = "Escribí una respuesta para la empresa."; return; } saving.value = true; try { const { data } = await api.put<SupportTicket>(`/superadmin/support/${selected.value.id}/reply`, reply); tickets.value = tickets.value.map(ticket => ticket.id === data.id ? data : ticket); selected.value = null; notify("Respuesta enviada a la empresa."); } catch (cause) { error.value = apiError(cause); } finally { saving.value = false; } }
let refreshTimer: ReturnType<typeof window.setInterval> | undefined;
function refreshWhenVisible() { if (document.visibilityState === "visible") void load(true); }
onMounted(() => { void load(); refreshTimer = window.setInterval(refreshWhenVisible, 15_000); window.addEventListener("focus", refreshWhenVisible); });
onBeforeUnmount(() => { if (refreshTimer) window.clearInterval(refreshTimer); window.removeEventListener("focus", refreshWhenVisible); });
</script>

<template>
  <div class="page-heading"><div><div class="breadcrumb">SuperAdmin / Consultas</div><h1>Consultas y tickets</h1><p>Respondé las consultas enviadas por las empresas de la plataforma.</p></div><button class="secondary" :disabled="loading" @click="() => load()"><RefreshCw :size="16" :class="{ spin: loading }" />Actualizar</button></div>
  <section class="panel"><div class="admin-support-toolbar"><label><Search :size="17" /><input v-model.trim="search" placeholder="Buscar empresa, cliente o asunto" /></label></div><p v-if="error" class="error" role="alert">{{ error }}</p><p v-else-if="loading" class="empty-small">Cargando consultas…</p><div v-else-if="filtered.length" class="responsive-table"><table><thead><tr><th>Empresa / Usuario</th><th>Consulta</th><th>Estado</th><th>Última actualización</th><th>Acciones</th></tr></thead><tbody><tr v-for="ticket in filtered" :key="ticket.id"><td><strong>{{ ticket.tenantName }}</strong><small>{{ ticket.userName }}</small></td><td><strong>{{ ticket.subject }}</strong><small>{{ ticket.message }}</small></td><td><span class="status" :class="statusClass(ticket.status)">{{ statusLabel(ticket.status) }}</span></td><td>{{ dateTime(ticket.updatedAtUtc) }}</td><td><button class="secondary compact" @click="open(ticket)"><MessageSquareText :size="15" />{{ ticket.response ? "Ver / responder" : "Responder" }}</button></td></tr></tbody></table></div><div v-else class="empty-state compact"><CheckCircle2 :size="34" /><h2>No hay consultas pendientes</h2><p>Las nuevas consultas aparecerán aquí.</p></div></section>
  <div v-if="selected" class="modal-backdrop"><section class="modal support-reply-modal"><button class="icon-button modal-close" aria-label="Cerrar" @click="selected = null"><X /></button><div class="modal-icon"><MessageSquareText /></div><h2>{{ selected.subject }}</h2><p class="muted">{{ selected.tenantName }} · {{ selected.userName }} · {{ dateTime(selected.createdAtUtc) }}</p><div class="ticket-message">{{ selected.message }}</div><form novalidate @submit.prevent="saveReply"><label>Respuesta<textarea v-model.trim="reply.response" rows="6" maxlength="4000" required /></label><label>Estado<select v-model.number="reply.status"><option :value="2">En progreso</option><option :value="3">Resuelto</option></select></label><p v-if="error" class="error">{{ error }}</p><button class="primary full" :disabled="saving"><LoaderCircle v-if="saving" class="spin" :size="16" /><Send v-else :size="16" />{{ saving ? "Enviando…" : "Enviar respuesta" }}</button></form></section></div>
</template>

<style scoped>
.admin-support-toolbar{display:flex;justify-content:flex-end;margin-bottom:1rem}.admin-support-toolbar label{display:flex;align-items:center;gap:.5rem;width:min(23rem,100%);padding:0 .7rem;border:1px solid #dbe3ef;border-radius:.65rem;color:#64748b}.admin-support-toolbar input{border:0;box-shadow:none}td small{display:block;max-width:30rem;margin-top:.25rem;color:#64748b}.compact{display:inline-flex;align-items:center;gap:.3rem;padding:.45rem .6rem;font-size:.75rem}.warning{background:#fef3c7;color:#92400e}.trial{background:#ede9fe;color:#6d28d9}.support-reply-modal{max-width:38rem}.ticket-message{margin:1rem 0;padding:.8rem;border-radius:.65rem;background:#f8fafc;white-space:pre-wrap;color:#334155}.dark .admin-support-toolbar label,.dark .admin-support-toolbar input{border-color:#475a77;background:#0f172a}.dark td small{color:#b8c7dc}.dark .ticket-message{background:#0f172a;color:#d1dced}@media(max-width:700px){.admin-support-toolbar label{width:100%}}
</style>
