<script setup lang="ts">
import { reactive, ref, watch } from "vue";
import { FolderPlus, LoaderCircle, Pencil, Plus, Tags, Trash2, X } from "lucide-vue-next";
import { api, apiError } from "../services/api";
import { useAuthStore } from "../stores/auth";
import type { Category } from "../types/api";

const auth = useAuthStore();
const categories = ref<Category[]>([]), loading = ref(false), saving = ref(false), error = ref(""), success = ref(""), showModal = ref(false), editing = ref<Category | null>(null);
const form = reactive({ name: "", description: "", isActive: true });
function reset(category?: Category) { editing.value = category || null; form.name = category?.name || ""; form.description = category?.description || ""; form.isActive = category?.isActive ?? true; error.value = ""; }
function open(category?: Category) { reset(category); showModal.value = true; }
async function load() { if (!auth.tenantId) return; loading.value = true; error.value = ""; try { categories.value = (await api.get<Category[]>("/categories", { params: { tenantId: auth.tenantId } })).data; } catch (cause) { error.value = apiError(cause); } finally { loading.value = false; } }
async function save() { if (!form.name.trim()) { error.value = "El nombre de la categoría es obligatorio."; return; } saving.value = true; error.value = ""; try { if (editing.value) await api.put(`/categories/${editing.value.id}`, { id: editing.value.id, tenantId: auth.tenantId, name: form.name.trim(), description: form.description.trim() || null, isActive: form.isActive }); else await api.post("/categories", { tenantId: auth.tenantId, name: form.name.trim(), description: form.description.trim() || null }); showModal.value = false; success.value = editing.value ? "Categoría actualizada." : "Categoría creada correctamente."; await load(); } catch (cause) { error.value = apiError(cause); } finally { saving.value = false; } }
async function remove(category: Category) { if (!window.confirm(`¿Eliminar la categoría “${category.name}”?`)) return; error.value = ""; try { await api.delete(`/categories/${category.id}`, { params: { tenantId: auth.tenantId } }); success.value = "Categoría eliminada."; await load(); } catch (cause) { error.value = apiError(cause); } }
watch(() => auth.tenantId, load, { immediate: true });
</script>
<template><div class="page-heading"><div><div class="breadcrumb">Tu negocio / Inventario</div><h1>Categorías de productos</h1><p>Organizá el catálogo para encontrar y vender más rápido.</p></div><button class="primary" @click="open()"><Plus :size="17"/>Nueva categoría</button></div><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="success" class="success" role="status">{{success}}</p><section class="panel"><div v-if="loading" class="empty-small"><LoaderCircle class="spin"/>Cargando categorías…</div><div v-else-if="!categories.length" class="empty-state"><Tags :size="40"/><h2>Todavía no hay categorías</h2><p>Creá la primera para clasificar tus productos y habilitar filtros en el POS.</p><button class="primary" @click="open()"><FolderPlus :size="17"/>Crear categoría</button></div><div v-else class="category-grid"><article v-for="category in categories" :key="category.id"><span class="category-icon"><Tags :size="20"/></span><div><h2>{{category.name}}</h2><p>{{category.description || "Sin descripción"}}</p><span :class="category.isActive?'status success-status':'status danger'">{{category.isActive?'Activa':'Inactiva'}}</span></div><div class="category-actions"><button class="icon-button" :aria-label="`Editar ${category.name}`" @click="open(category)"><Pencil :size="16"/></button><button class="icon-button danger-button" :aria-label="`Eliminar ${category.name}`" @click="remove(category)"><Trash2 :size="16"/></button></div></article></div></section><div v-if="showModal" class="modal-backdrop"><section class="modal"><button class="icon-button modal-close" @click="showModal=false"><X/></button><div class="modal-icon"><Tags/></div><h2>{{editing?'Editar categoría':'Nueva categoría'}}</h2><p v-if="error" class="error">{{error}}</p><form novalidate @submit.prevent="save"><label>Nombre<input v-model.trim="form.name" maxlength="100" required autofocus placeholder="Ej. Bebidas"/></label><label>Descripción <small>Opcional</small><textarea v-model.trim="form.description" maxlength="500" placeholder="Una breve descripción"/></label><label v-if="editing" class="toggle"><input v-model="form.isActive" type="checkbox"/><span><strong>Categoría activa</strong><small>Las categorías inactivas no aparecerán al crear productos.</small></span></label><button class="primary full" :disabled="saving"><LoaderCircle v-if="saving" class="spin" :size="16"/>{{saving?'Guardando…':'Guardar categoría'}}</button></form></section></div></template>
<style scoped>.category-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(255px,1fr));gap:1rem}.category-grid article{display:flex;gap:.8rem;padding:1.1rem;border:1px solid #e2e8f0;border-radius:.9rem}.category-icon{display:grid;place-items:center;width:2.5rem;height:2.5rem;border-radius:.7rem;background:#fdf2f8;color:#db2777}.category-grid h2{margin:0 0 .25rem}.category-grid p{min-height:2.7rem;font-size:.88rem}.category-actions{display:flex;align-self:flex-start;margin-left:auto;gap:.35rem}.danger-button{color:#e11d48}.toggle{grid-template-columns:auto 1fr;align-items:start}.toggle input{width:1rem;height:1rem;margin-top:.2rem;accent-color:#ec4899}.toggle span{display:grid;gap:.2rem}.toggle small{color:#64748b;font-weight:400}</style>
