<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { CheckCircle2, CreditCard, Landmark, LoaderCircle, Minus, Plus, ReceiptText, Search, ShoppingCart, Trash2, Wallet, X } from "lucide-vue-next";
import { api, apiError } from "../services/api";
import { useAuthStore } from "../stores/auth";
import { useTenantStore } from "../stores/tenant";
import type { AfipAuthorization, Category, Customer, PagedResult, Product } from "../types/api";
type CartLine = Product & { quantity: number };
const auth = useAuthStore(), tenant = useTenantStore();
const products = ref<Product[]>([]), customers = ref<Customer[]>([]), categories = ref<Category[]>([]), cart = ref<CartLine[]>([]);
const productSearch = ref(""), selectedCategory = ref(""), customerSearch = ref(""), selectedCustomer = ref<Customer | null>(null);
const discountPercent = ref(0), payment = ref(1), loading = ref(false), saving = ref(false), error = ref(""), success = ref("");
const invoiceId = ref(""), authorization = ref<AfipAuthorization | null>(null), showAfip = ref(false), showCustomer = ref(false), showPayment = ref(false);
const pendingNet = ref(0), pendingIva = ref(0);
const money = (value: number) => new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS" }).format(value);
const subtotal = computed(() => cart.value.reduce((total, item) => total + item.price * item.quantity, 0));
const discount = computed(() => Math.round(subtotal.value * Math.min(100, Math.max(0, discountPercent.value)) / 100 * 100) / 100);
const total = computed(() => subtotal.value - discount.value);
const net = computed(() => Math.round(total.value / 1.21 * 100) / 100);
const iva = computed(() => Math.round((total.value - net.value) * 100) / 100);
const visibleProducts = computed(() => products.value.filter(product => product.stock > 0 && (!selectedCategory.value || product.categoryId === selectedCategory.value) && `${product.sku} ${product.name}`.toLowerCase().includes(productSearch.value.toLowerCase())));
const visibleCustomers = computed(() => customers.value.filter(customer => `${customer.name} ${customer.documentNumber}`.toLowerCase().includes(customerSearch.value.toLowerCase())).slice(0, 8));
const availableCredit = computed(() => selectedCustomer.value ? Math.max(0, selectedCustomer.value.creditLimit - selectedCustomer.value.currentBalance) : 0);
const paymentOptions = [{ value: 1, label: "Efectivo", icon: Wallet }, { value: 4, label: "Transferencia", icon: Landmark }, { value: 2, label: "Tarjeta", icon: CreditCard }, { value: 6, label: "Cuenta corriente", icon: Wallet }];
async function loadCatalogs() { if (!auth.tenantId) return; loading.value = true; error.value = ""; const params = { tenantId: auth.tenantId, isActive: true, pageNumber: 1, pageSize: 100 }; const [p, c, cat] = await Promise.allSettled([api.get<PagedResult<Product>>("/products", { params }), api.get<PagedResult<Customer>>("/customers", { params }), api.get<Category[]>("/categories", { params: { tenantId: auth.tenantId } })]); if (p.status === "fulfilled") products.value = p.value.data.items; else error.value = apiError(p.reason); if (c.status === "fulfilled") { customers.value = c.value.data.items; selectedCustomer.value ||= customers.value.find(customer => customer.documentNumber === "00000000") || customers.value.find(customer => customer.taxCondition.toLowerCase().includes("consumidor")) || null; } else error.value ||= apiError(c.reason); if (cat.status === "fulfilled") categories.value = cat.value.data; loading.value = false; }
function add(product: Product) { const item = cart.value.find(line => line.id === product.id); if (item) { if (item.quantity < product.stock) item.quantity++; } else if (product.stock > 0) cart.value.push({ ...product, quantity: 1 }); }
function changeQuantity(item: CartLine, amount: number) { item.quantity = Math.max(1, Math.min(item.stock, item.quantity + amount)); }
function remove(id: string) { cart.value = cart.value.filter(item => item.id !== id); }
async function ensureConsumerFinal() {
  if (!auth.tenantId || selectedCustomer.value) return;
  const existing = customers.value.find(customer => customer.documentNumber === "00000000" || customer.taxCondition.toLowerCase().includes("consumidor"));
  if (existing) { selectedCustomer.value = existing; return; }
  try {
    const { data } = await api.get<PagedResult<Customer>>("/customers", { params: { tenantId: auth.tenantId, searchTerm: "00000000", isActive: true, pageNumber: 1, pageSize: 1 } });
    if (data.items[0]) { selectedCustomer.value = data.items[0]; return; }
    const created = await api.post("/customers", { tenantId: auth.tenantId, name: "Consumidor Final", legalName: "Consumidor Final", documentType: "DNI", documentNumber: "00000000", taxCondition: "Consumidor Final", email: "", phone: "", address: "", city: "", state: "", postalCode: "", creditLimit: 0, allowCredit: false });
    const id = createdId(created); if (id) { const detail = await api.get<Customer>(`/customers/${id}`, { params: { tenantId: auth.tenantId } }); customers.value.push(detail.data); selectedCustomer.value = detail.data; }
  } catch { /* A concurrent POS may have created it; the operator can still select a customer. */ }
}
function selectCustomer(customer: Customer) { selectedCustomer.value = customer; customerSearch.value = ""; showCustomer.value = false; }
function createdId(response: { data?: { id?: string }; headers?: any }) { const location = response.headers?.get?.("location") ?? response.headers?.location; return response.data?.id || (typeof location === "string" ? location.split("/").pop() : "") || ""; }
async function openPayment() { if (!cart.value.length || !tenant.activeWarehouseId) { error.value = "Elegí un depósito y al menos un producto para continuar."; return; } await ensureConsumerFinal(); if (!selectedCustomer.value) { error.value = "No pudimos preparar el cliente Consumidor Final. Intentá nuevamente."; return; } if (payment.value === 6 && (!selectedCustomer.value.allowCredit || total.value > availableCredit.value)) { error.value = "El cliente no tiene crédito disponible para esta venta."; return; } error.value = ""; showPayment.value = true; }
async function createSale() { saving.value = true; error.value = ""; success.value = ""; authorization.value = null; invoiceId.value = ""; try { const order = await api.post("/orders", { tenantId: auth.tenantId, customerId: selectedCustomer.value!.id, warehouseId: tenant.activeWarehouseId, discountAmount: discount.value, paymentMethod: payment.value, items: cart.value.map(item => ({ productId: item.id, quantity: item.quantity })) }); const orderId = createdId(order); if (!orderId) throw new Error("La API no devolvió el identificador de la venta."); const invoice = await api.post("/sales/invoices", { tenantId: auth.tenantId, orderId, number: `POS-${Date.now()}`, dueAtUtc: null }); invoiceId.value = createdId(invoice); pendingNet.value = net.value; pendingIva.value = iva.value; success.value = `Venta registrada por ${money(total.value)} con ${paymentOptions.find(option => option.value === payment.value)?.label.toLowerCase()}.`; cart.value = []; showPayment.value = false; } catch (cause) { error.value = apiError(cause); } finally { saving.value = false; } }
async function authorize() { if (!invoiceId.value) return; saving.value = true; error.value = ""; try { const { data } = await api.post<AfipAuthorization>(`/afip/invoices/${invoiceId.value}/authorize`, { tenantId: auth.tenantId, invoiceId: invoiceId.value, voucherType: 6, concept: 1, exemptAmount: 0, vatItems: [{ id: 5, baseAmount: pendingNet.value, amount: pendingIva.value }], serviceStartDate: null, serviceEndDate: null, paymentDueDate: null }); authorization.value = data; } catch (cause) { error.value = apiError(cause); } finally { showAfip.value = true; saving.value = false; } }
watch(() => auth.tenantId, loadCatalogs, { immediate: true }); watch(customers, () => { void ensureConsumerFinal(); }); watch(() => tenant.warehouses, (warehouses) => { if (!tenant.activeWarehouseId && warehouses.length === 1) tenant.activeWarehouseId = warehouses[0].id; }, { immediate: true }); onMounted(() => { if (!tenant.warehouses.length) void tenant.load(); });
</script>
<template>
  <div class="page-heading"><div><div class="breadcrumb">Tu negocio / Ventas</div><h1>Punto de venta</h1><p>Armá el comprobante, cobrá y autorizá en AFIP.</p></div><span class="badge">POS</span></div>
  <p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="success" class="success" role="status">{{ success }}</p>
  <div class="pos-layout" :aria-busy="loading"><section class="panel pos-catalog"><div class="section-heading"><div><h2>Productos</h2><p>Buscá y agregá en un toque</p></div><Search :size="19" class="muted" /></div><label class="search-input"><Search :size="17" /><input v-model="productSearch" placeholder="Buscar por nombre o SKU" /></label><div class="category-chips"><button :class="{ active: !selectedCategory }" @click="selectedCategory = ''">Todos</button><button v-for="category in categories" :key="category.id" :class="{ active: selectedCategory === category.id }" @click="selectedCategory = category.id">{{ category.name }}</button></div><div v-if="loading" class="empty-small"><LoaderCircle class="spin" /> Cargando catálogo…</div><div v-else class="product-picker"><button v-for="product in visibleProducts" :key="product.id" class="product-choice" :disabled="product.stock === 0" @click="add(product)"><span><strong>{{ product.name }}</strong><small>{{ product.sku }} · {{ product.stock }} disponibles</small></span><strong>{{ money(product.price) }}</strong><Plus :size="17" /></button><p v-if="!visibleProducts.length" class="empty-small">No encontramos productos activos.</p></div></section>
    <section class="panel pos-cart"><div class="section-heading"><div><h2>Venta actual</h2><p>{{ cart.length ? `${cart.length} producto(s) en el comprobante` : 'Sumá productos para comenzar' }}</p></div><ShoppingCart :size="20" class="muted" /></div><div class="customer-select"><label>Cliente<input v-model="customerSearch" placeholder="Buscar cliente" @focus="showCustomer = true" /></label><button v-if="selectedCustomer" class="selected-customer" @click="selectedCustomer = null"><span>{{ selectedCustomer.name }}<small>{{ selectedCustomer.documentNumber }}</small></span><X :size="16" /></button><div v-if="showCustomer && customerSearch" class="customer-results"><button v-for="customer in visibleCustomers" :key="customer.id" @click="selectCustomer(customer)"><strong>{{ customer.name }}</strong><small>{{ customer.documentNumber }}</small></button><p v-if="!visibleCustomers.length">No hay coincidencias.</p></div></div><label>Depósito / sucursal<select v-model="tenant.activeWarehouseId"><option value="">Elegí un depósito</option><option v-for="warehouse in tenant.warehouses" :key="warehouse.id" :value="warehouse.id">{{ warehouse.name }}</option></select></label><div class="cart-lines"><div v-for="item in cart" :key="item.id" class="cart-line"><div><strong>{{ item.name }}</strong><small>{{ money(item.price) }} c/u · stock {{ item.stock }}</small></div><div class="quantity"><button @click="changeQuantity(item, -1)"><Minus :size="14" /></button><span>{{ item.quantity }}</span><button :disabled="item.quantity >= item.stock" @click="changeQuantity(item, 1)"><Plus :size="14" /></button></div><strong>{{ money(item.price * item.quantity) }}</strong><button class="icon-button" @click="remove(item.id)"><Trash2 :size="17" /></button></div><p v-if="!cart.length" class="empty-small">El detalle de la venta aparecerá aquí.</p></div><label class="discount-control">Descuento (%)<input v-model.number="discountPercent" type="number" min="0" max="100" step="1" /></label><div class="totals"><span>Subtotal <strong>{{ money(subtotal) }}</strong></span><span v-if="discount">Descuento <strong>-{{ money(discount) }}</strong></span><span>IVA 21% <strong>{{ money(iva) }}</strong></span><span class="total">Total <strong>{{ money(total) }}</strong></span></div><button class="primary full" :disabled="saving || !cart.length" @click="openPayment"><CreditCard :size="17" />Ir a cobrar</button><button v-if="invoiceId" class="secondary full" :disabled="saving" @click="authorize"><CheckCircle2 :size="17" />Autorizar en AFIP</button></section></div>
  <div v-if="showPayment" class="modal-backdrop" @click.self="showPayment = false"><section class="modal"><button class="icon-button modal-close" @click="showPayment = false"><X /></button><div class="modal-icon"><CreditCard /></div><h2>Confirmá el cobro</h2><p>Seleccioná el medio de pago de esta venta.</p><div class="payment-methods"><button v-for="option in paymentOptions" :key="option.value" :disabled="option.value === 6 && (!selectedCustomer?.allowCredit || total > availableCredit)" :class="{ active: payment === option.value }" @click="payment = option.value"><component :is="option.icon" :size="20" /><span>{{ option.label }}<small v-if="option.value === 6">Disponible: {{ money(availableCredit) }}</small></span><CheckCircle2 v-if="payment === option.value" :size="17" /></button></div><div class="checkout-total">Total a cobrar <strong>{{ money(total) }}</strong></div><button class="primary full" :disabled="saving" @click="createSale"><LoaderCircle v-if="saving" class="spin" :size="17" /><ReceiptText v-else :size="17" />{{ saving ? 'Registrando…' : 'Confirmar venta' }}</button></section></div>
  <div v-if="showAfip" class="modal-backdrop" @click.self="showAfip = false"><section class="modal"><button class="icon-button modal-close" @click="showAfip = false"><X /></button><div class="modal-icon" :class="authorization?.isApproved ? 'approved' : 'rejected'"><CheckCircle2 v-if="authorization?.isApproved" /><ReceiptText v-else /></div><h2>{{ authorization?.isApproved ? 'Factura autorizada' : 'Resultado de AFIP' }}</h2><p>{{ authorization?.isApproved ? 'El comprobante fue autorizado correctamente.' : authorization?.errors || error || 'No pudimos obtener una autorización.' }}</p><dl v-if="authorization?.isApproved" class="authorization-data"><div><dt>CAE</dt><dd>{{ authorization.cae }}</dd></div><div><dt>Vencimiento</dt><dd>{{ authorization.caeExpirationDate }}</dd></div></dl><button class="primary full" @click="showAfip = false">Entendido</button></section></div>
</template>
