<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useRoute } from "vue-router";
import { Check, CreditCard, Crown, LoaderCircle, Sparkles, Users, Warehouse } from "lucide-vue-next";
import { api, apiError, notify } from "../services/api";
import { useAuthStore } from "../stores/auth";
import { useTenantStore } from "../stores/tenant";
import type { Subscription, SubscriptionPlan } from "../types/api";
const auth = useAuthStore();
const tenant = useTenantStore();
const route = useRoute();
const current = ref<Subscription | null>(null), plans = ref<SubscriptionPlan[]>([]), annual = ref(false), loading = ref(false), changing = ref(""), selectedPlan = ref<SubscriptionPlan | null>(null);
const canManage = computed(() => ["Owner", "Admin"].includes(auth.user?.role || ""));
const daysLeft = computed(() => current.value ? Math.max(0, Math.ceil((new Date(current.value.expiresAtUtc).getTime() - Date.now()) / 86400000)) : 0);
const statusLabel = (status: number) => ({ 1: "Activa", 2: "Pago pendiente", 3: "Cancelada", 4: "En prueba" }[status] || "Sin estado");
const price = (plan: SubscriptionPlan) => new Intl.NumberFormat("es-AR", { style: "currency", currency: plan.currency || "ARS", maximumFractionDigits: 0 }).format(annual.value ? plan.annualPrice : plan.monthlyPrice);
async function load() { if (!auth.tenantId) return; loading.value = true; try { const [subscription, availablePlans] = await Promise.all([api.get<Subscription | null>("/subscription/current", { params: { tenantId: auth.tenantId } }), api.get<SubscriptionPlan[]>("/subscription/plans")]); current.value = subscription.data; plans.value = availablePlans.data; } catch (cause) { notify(apiError(cause), true); } finally { loading.value = false; } }
function requestPlanChange(plan: SubscriptionPlan) { if (canManage.value) selectedPlan.value = plan; }
async function changePlan() { const plan = selectedPlan.value; if (!plan) return; changing.value = plan.id; try { const { data } = await api.post<{ checkoutUrl: string; isSimulated: boolean }>("/subscription/checkout", { tenantId: auth.tenantId, subscriptionPlanId: plan.id, annualBilling: annual.value, autoRenew: true, paymentProvider: "MercadoPago" }); selectedPlan.value = null; if (data.isSimulated) { await load(); await tenant.load(); notify(`Plan ${plan.name} activado en modo de prueba. Los nuevos límites ya están vigentes.`); } else window.location.assign(data.checkoutUrl); } catch (cause) { notify(apiError(cause), true); } finally { changing.value = ""; } }
watch(() => auth.tenantId, load, { immediate: true });
</script>
<template>
  <div class="page-heading"><div><div class="breadcrumb">Tu negocio / Suscripción</div><h1>Planes y suscripción</h1><p>Elegí el plan que acompaña el crecimiento de tu negocio.</p></div></div>
  <p v-if="route.query.expired === 'trial'" class="subscription-alert" role="alert">Tu periodo de prueba de 7 días ha finalizado. Seleccioná un plan para continuar utilizando el sistema.</p><p v-else-if="route.query.expired === 'plan'" class="subscription-alert" role="alert">Tu suscripción no está activa. Seleccioná un plan para continuar utilizando el sistema.</p>
  <section v-if="current && (current.status === 2 || daysLeft <= 7)" class="subscription-alert"><CreditCard :size="21" /><div><strong>{{ current.status === 2 ? "Tu suscripción requiere regularización" : "Tu suscripción está próxima a vencer" }}</strong><p>Plan {{ current.planName }} · {{ daysLeft }} día(s) restantes.</p></div></section>
  <section v-if="current" class="current-plan panel"><div><span class="badge">{{ statusLabel(current.status) }}</span><h2>Plan {{ current.planName }}</h2><p>Vence el {{ new Date(current.expiresAtUtc).toLocaleDateString("es-AR") }} · {{ daysLeft }} día(s) restantes.</p></div><Crown :size="40" /><small>Renovación automática: {{ current.autoRenew ? "activa" : "desactivada" }}</small></section>
  <div v-if="loading" class="empty-small"><LoaderCircle class="spin" /> Cargando planes…</div><section v-else class="plans-grid"><article v-for="plan in plans" :key="plan.id" class="plan-card" :class="{ featured: plan.name === 'Pro' }"><span v-if="plan.name === 'Pro'" class="popular">MÁS ELEGIDO</span><h2>{{ plan.name }}</h2><p class="plan-price">{{ price(plan) }}<small>/ {{ annual ? "año" : "mes" }}</small></p><label class="billing-switch"><input v-model="annual" type="checkbox" /> Facturación anual</label><ul><li><Check :size="16" />{{ plan.maxUsers }} usuarios</li><li><Warehouse :size="16" />{{ plan.maxWarehouses }} depósito(s)</li><li><Users :size="16" />{{ plan.maxInvoicesPerMonth.toLocaleString("es-AR") }} comprobantes/mes</li><li><Check :size="16" />{{ plan.supportsAfip ? "Facturación ARCA incluida" : "Ticket interno y gestión base" }}</li></ul><button class="primary full" :disabled="!canManage || changing === plan.id || current?.subscriptionPlanId === plan.id" @click="requestPlanChange(plan)"><LoaderCircle v-if="changing === plan.id" class="spin" :size="16" /><Sparkles v-else :size="16" />{{ current?.subscriptionPlanId === plan.id ? "Plan actual" : "Cambiar a este plan" }}</button></article></section>
  <div v-if="selectedPlan" class="modal-backdrop" @click.self="!changing && (selectedPlan = null)"><section class="modal plan-confirm" role="dialog" aria-modal="true" aria-labelledby="plan-confirm-title"><button class="icon-button modal-close" aria-label="Cerrar" :disabled="!!changing" @click="selectedPlan = null">×</button><div class="modal-icon"><CreditCard /></div><h2 id="plan-confirm-title">Confirmar cambio de plan</h2><p>Vas a pasar al plan <strong>{{ selectedPlan.name }}</strong> por <strong>{{ price(selectedPlan) }}</strong> {{ annual ? "al año" : "por mes" }}.</p><p class="muted">Con credenciales configuradas continuarás al checkout seguro. En modo de prueba se activa de inmediato.</p><div class="modal-actions"><button class="secondary" :disabled="!!changing" @click="selectedPlan = null">Cancelar</button><button class="primary" :disabled="!!changing" @click="changePlan"><LoaderCircle v-if="changing" class="spin" :size="16" />{{ changing ? "Procesando…" : "Continuar" }}</button></div></section></div>
</template>
<style scoped>
.subscription-alert { display:flex; gap:.8rem; align-items:flex-start; padding:1rem 1.15rem; margin-bottom:1rem; border:1px solid #fda4af; border-radius:.85rem; color:#be123c; background:#fff1f2; } .subscription-alert p { margin:.2rem 0 0; } .current-plan { display:grid; grid-template-columns:1fr auto; gap:.5rem 1rem; margin-bottom:1rem; background:linear-gradient(110deg,#fff,#fdf2f8); } .current-plan h2 { margin:.55rem 0 .25rem; } .current-plan p,.current-plan small { margin:0; color:#64748b; } .current-plan small { grid-column:1/-1; } .plans-grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(250px,1fr)); gap:1rem; } .plan-card { position:relative; padding:1.3rem; border:1px solid #e2e8f0; border-radius:1rem; background:#fff; box-shadow:0 1px 2px rgba(15,23,42,.04); } .plan-card.featured { border:2px solid #ec4899; box-shadow:0 10px 25px rgba(236,72,153,.13); } .popular { position:absolute; top:-.7rem; right:1rem; padding:.25rem .55rem; border-radius:999px; color:white; background:#ec4899; font-size:.68rem; font-weight:800; } .plan-card h2 { margin:0; } .plan-price { margin:.85rem 0; color:#0f172a; font-size:1.8rem; font-weight:800; } .plan-price small { color:#64748b; font-size:.8rem; font-weight:400; } .billing-switch { display:flex; gap:.5rem; align-items:center; color:#475569; font-size:.86rem; } .billing-switch input { width:1rem; height:1rem; accent-color:#ec4899; } ul { display:grid; gap:.65rem; padding:0; margin:1.1rem 0; list-style:none; color:#475569; } li { display:flex; align-items:center; gap:.5rem; } li svg { color:#db2777; }
.plan-confirm{max-width:31rem}.modal-actions{display:flex;justify-content:flex-end;gap:.75rem;margin-top:1.35rem}.modal-actions button{min-width:8rem}
</style>
