<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from "vue";
import { ChevronDown, LifeBuoy, LoaderCircle, MessageCircleMore, Plus, Send } from "lucide-vue-next";
import { api, apiError, notify } from "../services/api";
import { dateTime } from "../services/format";
import type { SupportTicket } from "../types/api";

const tickets = ref<SupportTicket[]>([]), loading = ref(false), sending = ref(false), replying = ref(false), error = ref(""), openTicketId = ref<string | null>(null);
const form = reactive({ subject: "", message: "" });
const replies = reactive<Record<string, string>>({});
const statusLabel = (status: number) => ({ 1: "Abierto", 2: "En progreso", 3: "Resuelto" }[status] || "Abierto");
const statusClass = (status: number) => ({ 1: "warning", 2: "trial", 3: "success-status" }[status] || "warning");
const openTickets = computed(() => tickets.value.filter(ticket => ticket.status !== 3).length);
async function load(silent = false) { if (!silent) { loading.value = true; error.value = ""; } try { tickets.value = (await api.get<SupportTicket[]>("/support")).data; } catch (cause) { if (!silent) error.value = apiError(cause); } finally { if (!silent) loading.value = false; } }
async function submit() { if (!form.subject.trim() || !form.message.trim()) { error.value = "Completá el asunto y el mensaje de tu consulta."; return; } sending.value = true; error.value = ""; try { const { data } = await api.post<SupportTicket>("/support", form); tickets.value = [data, ...tickets.value]; openTicketId.value = data.id; form.subject = ""; form.message = ""; notify("Tu consulta fue enviada al equipo de soporte."); } catch (cause) { error.value = apiError(cause); } finally { sending.value = false; } }
function toggle(ticket: SupportTicket) { openTicketId.value = openTicketId.value === ticket.id ? null : ticket.id; }
async function reply(ticket: SupportTicket) { const message = replies[ticket.id]?.trim(); if (!message) return; replying.value = true; try { const { data } = await api.post<SupportTicket>(`/support/${ticket.id}/messages`, { message }); tickets.value = tickets.value.map(item => item.id === data.id ? data : item); replies[ticket.id] = ""; notify("Tu respuesta fue enviada a soporte."); } catch (cause) { error.value = apiError(cause); } finally { replying.value = false; } }
let refreshTimer: ReturnType<typeof window.setInterval> | undefined;
function refreshWhenVisible() { if (document.visibilityState === "visible") void load(true); }
onMounted(() => { void load(); refreshTimer = window.setInterval(refreshWhenVisible, 15_000); window.addEventListener("focus", refreshWhenVisible); });
onBeforeUnmount(() => { if (refreshTimer) window.clearInterval(refreshTimer); window.removeEventListener("focus", refreshWhenVisible); });
</script>

<template>
  <div class="page-heading"><div><div class="breadcrumb">Tu negocio / Soporte</div><h1>Soporte y ayuda</h1><p>Creá una consulta y continuá la conversación con el equipo de SalesSaaS.</p></div></div>
  <section class="support-grid"><form class="panel support-form" novalidate @submit.prevent="submit"><div class="support-icon"><LifeBuoy :size="23" /></div><h2>Nueva consulta</h2><p>Contanos qué ocurrió y te responderemos por este mismo canal.</p><label>Asunto<input v-model.trim="form.subject" maxlength="200" placeholder="Ej. No puedo emitir un comprobante" /></label><label>Mensaje<textarea v-model.trim="form.message" maxlength="4000" rows="6" placeholder="Contanos qué ocurrió y qué estabas intentando hacer." /></label><p v-if="error" class="error" role="alert">{{ error }}</p><button class="primary full" :disabled="sending"><LoaderCircle v-if="sending" class="spin" :size="16" /><Send v-else :size="16" />{{ sending ? "Enviando…" : "Enviar consulta" }}</button></form>
    <section class="panel support-history"><div class="section-heading"><div><h2>Conversaciones</h2><p class="muted">{{ openTickets ? `${openTickets} conversación(es) abierta(s).` : "No tenés conversaciones abiertas." }}</p></div><button class="icon-button" title="Actualizar" @click="() => load()"><Plus :size="17" /></button></div><p v-if="loading" class="empty-small">Cargando conversaciones…</p><div v-else-if="!tickets.length" class="empty-state compact"><LifeBuoy :size="34" /><h2>Todavía no enviaste consultas</h2><p>Cuando necesites ayuda, escribinos desde el formulario.</p></div><article v-for="ticket in tickets" v-else :key="ticket.id" class="conversation" :class="{ expanded: openTicketId === ticket.id }"><button class="conversation-title" @click="toggle(ticket)"><div><strong>{{ ticket.subject }}</strong><small>Iniciada {{ dateTime(ticket.createdAtUtc) }}</small></div><div class="conversation-meta"><span v-if="ticket.messages.some(message => message.isFromSupport)" class="reply-badge"><MessageCircleMore :size="14" /> Con respuesta</span><span class="status" :class="statusClass(ticket.status)">{{ statusLabel(ticket.status) }}</span><ChevronDown :size="18" :class="{ rotated: openTicketId === ticket.id }" /></div></button><div v-if="openTicketId === ticket.id" class="conversation-body"><div class="message customer"><small>Vos · {{ dateTime(ticket.createdAtUtc) }}</small><p>{{ ticket.message }}</p></div><div v-for="message in ticket.messages" :key="message.id || `${message.createdAtUtc}-${message.message}`" class="message" :class="message.isFromSupport ? 'support' : 'customer'"><small>{{ message.isFromSupport ? "Soporte" : "Vos" }} · {{ dateTime(message.createdAtUtc) }}</small><p>{{ message.message }}</p></div><form v-if="ticket.status !== 3" class="reply-form" @submit.prevent="reply(ticket)"><textarea v-model.trim="replies[ticket.id]" rows="3" maxlength="4000" placeholder="Escribí una respuesta para continuar esta conversación" /><button class="primary" :disabled="replying || !replies[ticket.id]?.trim()"><LoaderCircle v-if="replying" class="spin" :size="16" /><Send v-else :size="16" />Responder</button></form><p v-else class="closed-message">Esta conversación fue resuelta y está cerrada.</p></div></article></section>
  </section>
</template>

<style scoped>
.support-grid{display:grid;grid-template-columns:minmax(18rem,.85fr) minmax(0,1.4fr);gap:1rem}.support-form{align-self:start}.support-icon{display:grid;place-items:center;width:2.7rem;height:2.7rem;border-radius:.75rem;background:#fdf2f8;color:#ec4899}.support-form h2{margin:.75rem 0 .25rem}.support-form>p{margin:0 0 1rem;color:#64748b}.support-history{min-height:24rem}.conversation{border-top:1px solid #e2e8f0}.conversation-title{display:flex;width:100%;align-items:center;justify-content:space-between;gap:1rem;padding:1rem 0;text-align:left;background:transparent;border:0;color:inherit}.conversation-title strong,.conversation-title small{display:block}.conversation-title small,.message small{margin-top:.25rem;color:#64748b;font-size:.75rem}.conversation-meta{display:flex;align-items:center;gap:.5rem}.reply-badge{display:inline-flex;align-items:center;gap:.25rem;padding:.25rem .45rem;border-radius:999px;background:#fdf2f8;color:#db2777;font-size:.72rem;font-weight:750}.rotated{transform:rotate(180deg)}.conversation-body{padding:0 0 1rem}.message{max-width:88%;margin:.55rem 0;padding:.7rem .8rem;border-radius:.7rem}.message p{margin:.3rem 0 0;white-space:pre-wrap}.message.customer{margin-left:auto;background:#f1f5f9;color:#334155}.message.support{background:#ecfdf5;color:#065f46}.reply-form{display:grid;grid-template-columns:1fr auto;gap:.65rem;margin-top:1rem}.reply-form textarea{min-height:2.8rem}.reply-form button{align-self:end}.closed-message{margin:.8rem 0 0;color:#64748b;font-size:.88rem}.trial{background:#ede9fe;color:#6d28d9}.warning{background:#fef3c7;color:#92400e}.dark .conversation{border-color:#334155}.dark .support-form>p,.dark .conversation-title small,.dark .message small,.dark .closed-message{color:#b8c7dc}.dark .message.customer{background:#1e293b;color:#e2e8f0}.dark .message.support{background:#173a35;color:#a7f3d0}.dark .reply-badge{background:#4a203d;color:#f9a8d4}@media(max-width:850px){.support-grid{grid-template-columns:1fr}.reply-form{grid-template-columns:1fr}.reply-form button{width:100%}}
</style>
