<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import { Building2, LoaderCircle, Pencil, Plus, Warehouse as WarehouseIcon, X } from "lucide-vue-next";
import { api, apiError } from "../services/api";
import { useAuthStore } from "../stores/auth";
import { useTenantStore } from "../stores/tenant";
import type { Warehouse } from "../types/api";
import { requiredText } from "../utils/validation";

const auth = useAuthStore();
const tenant = useTenantStore();
const warehouses = ref<Warehouse[]>([]), loading = ref(false), saving = ref(false), error = ref(""), success = ref(""), showModal = ref(false), editing = ref<Warehouse | null>(null);
const form = reactive({ code: "", name: "", address: "", isActive: true });
const canManage = computed(() => ["Owner", "Admin", "Warehouse"].includes(auth.user?.role || ""));
function resetForm(warehouse?: Warehouse) { editing.value = warehouse || null; Object.assign(form, warehouse ? { code: warehouse.code, name: warehouse.name, address: warehouse.address || "", isActive: warehouse.isActive } : { code: `SUC-${warehouses.value.length + 1}`, name: "", address: "", isActive: true }); }
function open(warehouse?: Warehouse) { resetForm(warehouse); error.value = ""; showModal.value = true; }
async function load() { if (!auth.tenantId) return; loading.value = true; error.value = ""; try { warehouses.value = (await api.get<Warehouse[]>("/warehouses", { params: { tenantId: auth.tenantId } })).data; } catch (cause) { error.value = apiError(cause); } finally { loading.value = false; } }
async function save() { const validation = requiredText(form.name, "El nombre", 100) || (!editing.value && requiredText(form.code, "El código", 30)); if (validation) { error.value = validation; return; } saving.value = true; error.value = ""; try { if (editing.value) await api.put(`/warehouses/${editing.value.id}`, { id: editing.value.id, tenantId: auth.tenantId, name: form.name.trim(), address: form.address.trim() || null, isActive: form.isActive }); else await api.post("/warehouses", { tenantId: auth.tenantId, code: form.code.trim(), name: form.name.trim(), address: form.address.trim() || null }); showModal.value = false; success.value = editing.value ? "Depósito actualizado." : "Depósito creado."; await load(); await tenant.load(); } catch (cause) { error.value = apiError(cause); } finally { saving.value = false; } }
watch(() => auth.tenantId, load, { immediate: true });
</script>
<template>
  <div class="page-heading"><div><div class="breadcrumb">Tu negocio / Configuración</div><h1>Depósitos y sucursales</h1><p>Definí desde dónde se vende, gestiona el stock y opera la caja.</p></div><button v-if="canManage" class="primary" @click="open()"><Plus :size="17" />Nuevo depósito</button></div>
  <p v-if="error && !showModal" class="error" role="alert">{{ error }}</p><p v-if="success" class="success" role="status">{{ success }}</p>
  <section class="panel"><div v-if="loading" class="empty-small"><LoaderCircle class="spin" /> Cargando depósitos…</div><div v-else-if="!warehouses.length" class="empty-state compact"><WarehouseIcon :size="36" /><h2>No hay depósitos cargados</h2><p>Creá uno para poder operar ventas y movimientos de stock.</p><button v-if="canManage" class="primary" @click="open()">Crear depósito</button></div><div v-else class="warehouse-grid"><article v-for="warehouse in warehouses" :key="warehouse.id" class="warehouse-card"><div class="warehouse-symbol"><Building2 :size="21" /></div><div class="warehouse-content"><div><span :class="warehouse.isActive ? 'status success-status' : 'status danger'">{{ warehouse.isActive ? 'Activo' : 'Inactivo' }}</span><h2>{{ warehouse.name }}</h2><p><strong>{{ warehouse.code }}</strong><span v-if="warehouse.address"> · {{ warehouse.address }}</span><span v-else> · Sin dirección registrada</span></p></div><button v-if="canManage" class="icon-button" :aria-label="`Editar ${warehouse.name}`" @click="open(warehouse)"><Pencil :size="17" /></button></div></article></div></section>
  <div v-if="showModal" class="modal-backdrop" @click.self="showModal = false"><section class="modal product-modal"><button class="icon-button modal-close" @click="showModal = false"><X /></button><div class="modal-icon"><Building2 /></div><h2>{{ editing ? 'Editar depósito' : 'Nuevo depósito' }}</h2><p v-if="error" class="error">{{ error }}</p><form @submit.prevent="save"><div class="form-grid"><label>Código<input v-model.trim="form.code" maxlength="30" :disabled="Boolean(editing)" required /></label><label>Nombre<input v-model.trim="form.name" maxlength="100" required autofocus /></label><label class="wide">Dirección<input v-model.trim="form.address" maxlength="250" placeholder="Ej. Av. Siempre Viva 123" /></label><label v-if="editing" class="warehouse-toggle"><input v-model="form.isActive" type="checkbox" /><span><strong>Depósito activo</strong><small>Los depósitos inactivos no estarán disponibles en el POS.</small></span></label></div><button class="primary full" :disabled="saving"><LoaderCircle v-if="saving" class="spin" :size="16" />{{ saving ? 'Guardando…' : 'Guardar depósito' }}</button></form></section></div>
</template>
<style scoped>
.warehouse-grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); gap:1rem; } .warehouse-card { padding:1rem; border:1px solid #e2e8f0; border-radius:.9rem; background:#fff; box-shadow:0 1px 2px rgba(15,23,42,.04); } .warehouse-symbol { display:grid; place-items:center; width:2.55rem; height:2.55rem; border-radius:.75rem; color:#db2777; background:#fce7f3; } .warehouse-content { display:flex; align-items:flex-start; justify-content:space-between; gap:.7rem; margin-top:.9rem; } .warehouse-content h2 { margin:.45rem 0 .25rem; font-size:1.05rem; color:#0f172a; } .warehouse-content p { margin:0; color:#64748b; font-size:.86rem; } .warehouse-content p strong { color:#475569; } .warehouse-toggle { grid-column:span 2; display:flex; align-items:center; gap:.75rem; min-height:64px; padding:.75rem .9rem; border:1px solid #e2e8f0; border-radius:.75rem; cursor:pointer; } .warehouse-toggle input { width:1.15rem; height:1.15rem; min-width:1.15rem; margin:0; padding:0; accent-color:#ec4899; } .warehouse-toggle span { display:grid; gap:.15rem; color:#0f172a; } .warehouse-toggle small { color:#64748b; font-size:.78rem; font-weight:400; } @media(max-width:640px) { .warehouse-toggle { grid-column:span 1; } }
</style>
